assets: /workspace/libero_rollout_envs/LIBERO/libero/libero/assets
bddl_files: /workspace/libero_rollout_envs/LIBERO/libero/libero/bddl_files
benchmark_root: /workspace/libero_rollout_envs/LIBERO/libero/libero
datasets: /workspace/vla-temporal-compression-baseline-data/libero_sim_datasets
init_states: /workspace/libero_rollout_envs/LIBERO/libero/libero/init_files
